/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinyButton: typeof import('@opentiny/vue-button')['default']
    TinyCard: typeof import('@opentiny/vue-card')['default']
    TinyCol: typeof import('@opentiny/vue-col')['default']
    TinyDatePicker: typeof import('@opentiny/vue-date-picker')['default']
    TinyFileUpload: typeof import('@opentiny/vue-file-upload')['default']
    TinyForm: typeof import('@opentiny/vue-form')['default']
    TinyFormItem: typeof import('@opentiny/vue-form-item')['default']
    TinyGrid: typeof import('@opentiny/vue-grid')['default']
    TinyGridColumn: typeof import('@opentiny/vue-grid-column')['default']
    TinyInput: typeof import('@opentiny/vue-input')['default']
    TinyOption: typeof import('@opentiny/vue-option')['default']
    TinyRow: typeof import('@opentiny/vue-row')['default']
    TinySelect: typeof import('@opentiny/vue-select')['default']
    TinyTag: typeof import('@opentiny/vue-tag')['default']
    VanIcon: typeof import('vant/es')['Icon']
  }
}
